spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: argumentoleg@gmail.com
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.debug: true



  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: com.zhvavyy.backend.kafka.messaging.dto.DataForSendEmail:com.zhvavyy.sender.dto.DataForSendEmail
    bootstrap-servers: kafka:9092
