spring:
  mail:
    host: in-v3.mailjet.com
    port: 465
    username: ${SPRING_MAILJET_NAME}
    password: ${SPRING_MAILJET_PASSWORD}
    from: argumentoleg@gmail.com
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.checkserveridentity: false
      mail.smtp.ssl.trust: in-v3.mailjet.com
      mail.smtp.starttls.enable: false
      mail.debug: true




  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
         com.zhvavyy.backend.kafka.messaging.dto.MessageForEmail:com.zhvavyy.sender.dto.MessageForEmail,
         com.zhvavyy.scheduler.kafka.messaging.dto.MessageForEmail:com.zhvavyy.sender.dto.MessageForEmail
    bootstrap-servers: kafka:9092


app:
  kafka:
    topics:
      email-sending: EMAIL_SENDING_TASKS
      user-registration: USER_REGISTRATION
