services:
  database:
    image: postgres:17
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    secrets:
      - db_user
      - db_password
      - db_name
    ports:
     - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  task-tracker-backend:
    image: olegzv13/backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      default:
        aliases:
          - backend
    secrets:
      - db_user
      - db_password
      - db_name
      - jwt_private_key
      - jwt_public_key
    entrypoint:  ["/entrypoint.sh"]
networks:
    default:
      driver: overlay

secrets:
  db_user:
    external: true
  db_password:
    external: true
  db_name:
    external: true
  jwt_private_key:
    external: true
  jwt_public_key:
    external: true



