services:
  database:
    image: postgres:17
    ports:
      - "5434:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass






  kafka:
      image: 'apache/kafka:4.0.0'
      ports:
          - "9092:9092"
      environment:
          - KAFKA_ENABLE_KRAFT=yes
          - KAFKA_PROCESS_ROLES=broker,controller
          - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
          - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
          - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
          - KAFKA_BROKER_ID=1
          - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
          - ALLOW_PLAINTEXT_LISTENER=yes
          - KAFKA_KRAFT_CLUSTER_ID=S40B8iVtR0umuTyuM1eLjA
          - KAFKA_NODE_ID=1
  ui:
        image: provectuslabs/kafka-ui:v0.7.1
        ports:
          - "8080:8080"
        environment:
          - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
          - KAFKA_CLUSTERS_0_NAME=kraft
  #      - DYNAMIC_CONFIG_ENABLED=true


