services:
  database:
    image: postgres:17
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    secrets:
      - db_user
      - db_password
      - db_name
    ports:
     - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - database

  task-tracker-email-sender:
    image: olegzv13/email-sender:2.5.RELEASE
    depends_on:
      - kafka
    secrets:
      - api_key
      - secret_key
    entrypoint: ["/entrypoint.sh"]
    networks:
      - default


  task-tracker-backend:
    image: olegzv13/backend:4.7.4.RELEASE
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - database
    networks:
      - default

    secrets:
      - db_user
      - db_password
      - db_name
      - jwt_private_key
      - jwt_public_key
    entrypoint: [ "/entrypoint.sh" ]


  task-tracker-scheduler:
    image: olegzv13/scheduler:1.7.2.RELEASE
    depends_on:
      - kafka
      - task-tracker-backend
    networks:
      - default


  task-tracker-frontend:
    image: olegzv13/frontend:4.0.RELEASE
    ports:
      - "80:80"
    depends_on:
      - task-tracker-backend
    networks:
      - default

  kafka:
    image: apache/kafka:4.0.0
    ports:
      - "9092:9092"
    hostname: kafka
    user: "1000:1000"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_BROKER_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_KRAFT_CLUSTER_ID_FILE=/run/secrets/kafka_cluster_id
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_LOG_RETENTION_HOURS=100
      - KAFKA_NUM_PARTITIONS=4
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes #заменить на SSL/TLS
      - KAFKA_CREATE_TOPICS=EMAIL_SENDING_TASKS:3:1, USER_REGISTRATION:3:1

    volumes:
      - kafka-data:/var/lib/kafka/data
    secrets:
      - kafka_cluster_id
    networks:
      - default


networks:
  default:
    driver: overlay
    attachable: true

volumes:
  kafka-data: {}
  pgdata:

secrets:
  db_user:
    external: true
  db_password:
    external: true
  db_name:
    external: true
  jwt_private_key:
    external: true
  jwt_public_key:
    external: true
  kafka_cluster_id:
    external: true
  api_key:
    external: true
  secret_key:
    external: true



