spring:
  application:
    name: task-tracker-backend

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

        #ИСПРАВИТЬ на хранение в сикрет докер
jwt:
  private-key: ${JWT_PRIVATE_KEY_PATH}
  public-key: ${JWT_PUBLIC_KEY_PATH}