spring:
  application:
    name: task-tracker-backend

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver



jwt:
    private-key: ${SPRING_JWT_PRIVATE_KEY}
    public-key: ${SPRING_JWT_PUBLIC_KEY}