spring:
  application:
    name: task-tracker-scheduler

  kafka:
    producer:
     key-serializer: org.apache.kafka.common.serialization.StringSerializer
     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: kafka:9092

task:
  cron:
    expression: 0 */1 * * * *

app:
  kafka:
    topics:
      email-sending: EMAIL_SENDING_TASKS

grpc:
  client:
    user-service:
      address: task-tracker-backend:9090
      negotiation-type: plaintext
    task-service:
      address: task-tracker-backend:9090
      negotiation-type: plaintext
    GLOBAL:
      security:
        client-auth-enabled: false

logging:
  level:
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG
    com.zhvavyy.backend.messaging.producer: DEBUG
