name: Tests-Build-Push-Services

on:
  push:
    branches:
      - main
    paths:
      - 'task-tracker-backend/**'
      - 'task-tracker-email-sender/**'
      - 'task-tracker-frontend/**'
      - 'task-tracker-scheduler/**'

env:
 BUILD_PACKAGE_NAME: "git-${{ github.sha }}"
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker image backend
        run: |
             docker build \
             -t ${{ secrets.DOCKER_HUB_OWNER }}/backend:${{ env.BUILD_PACKAGE_NAME}} \
             -t olegzv13/backend:latest ./task-tracker-backend


      - name: Build docker image email-sender
        run: |
             docker build  \
             -t ${{ secrets.DOCKER_HUB_OWNER }}/email-sender:${{ env.BUILD_PACKAGE_NAME }} \
             -t olegzv13/email-sender:latest ./task-tracker-email-sender


      - name: Build docker image frontend
        run: |
             docker build \
             -t ${{ secrets.DOCKER_HUB_OWNER }}/frontend:${{ env.BUILD_PACKAGE_NAME }} \
             -t olegzv13/frontend:latest ./task-tracker-frontend


      - name: Build docker image scheduler
        run: |
             docker build \
             -t ${{ secrets.DOCKER_HUB_OWNER }}/scheduler:${{ env.BUILD_PACKAGE_NAME }} \
             -t olegzv13/scheduler:latest ./task-tracker-scheduler


  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-images

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_OWNER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_HUB_OWNER }}/backend:${{env.BUILD_PACKAGE_NAME}}
          docker push ${{ secrets.DOCKER_HUB_OWNER }}/backend:latest
          
          docker push ${{ secrets.DOCKER_HUB_OWNER }}/email-sender:${{env.BUILD_PACKAGE_NAME}}
          docker push ${{ secrets.DOCKER_HUB_OWNER }}/email-sender:latest
          
          docker push ${{ secrets.DOCKER_HUB_OWNER }}/frontend:${{env.BUILD_PACKAGE_NAME}}
          docker push ${{ secrets.DOCKER_HUB_OWNER }}/frontend:latest
          
          docker push ${{ secrets.DOCKER_HUB_OWNER }}/scheduler:${{env.BUILD_PACKAGE_NAME}}
          docker push ${{ secrets.DOCKER_HUB_OWNER }}/scheduler:latest
